{% set name = "alignn" %}
{% set version = "2024.12.02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/alignn/archive/refs/tags/v{{ version }}.tar.gz
  sha256: da1c6ca6da3a22d997a1ee064a6b85628e89e4d7729154db6c3b12ce51175c1f

build:
  noarch: python 
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools 
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.19.5,<2.0.0
    - scipy >=1.6.1
    - jarvis-tools >=2021.07.19
    - pytorch >=2.0.0
    - mpmath >=1.3.0
    - dgl >=0.6.0
    - spglib >=2.0.2
    - scikit-learn >=0.22.2
    - matplotlib-base >=3.4.1
    - tqdm >=4.60.0
    - pandas >=1.2.3
    - pydantic >=1.8.1
    - pydantic-settings
    - flake8 >=3.9.1
    - pycodestyle >=2.7.0
    - pydocstyle >=6.0.0
    - pyparsing >=2.2.1,<3
    - ase
    - python-lmdb

test:
  imports:
    - alignn
  commands:
    - pip check
    - train_alignn.py -h
  requires:
    - pip
about:
  home: https://github.com/usnistgov/alignn
  summary: Atomistic Line Graph Neural Network & force-field
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
